env:
  browser: true
extends: 'eslint:recommended'
parser: "babel-eslint"
rules:
  no-console:
    - 1
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
